version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: fruitveg-api
    ports:
      - "8000:8000"
    volumes:
      - ./data/price_list.csv:/app/data/price_list.csv
    restart: unless-stopped

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    ports:
      - "8501:8501"
    depends_on:
      - api
    restart: unless-stopped