FROM python:3.12.3-slim

WORKDIR /app

RUN pip install --no-cache-dir streamlit requests tomli

COPY frontend ./frontend
COPY config.toml .

EXPOSE 8501
CMD ["streamlit", "run", "frontend/app_upload.py", "--server.port", "8501", "--server.address", "0.0.0.0"]
