FROM python:3.12.3-slim
WORKDIR /app

COPY requirements_deploy.txt .
RUN pip install --no-cache-dir -r requirements_deploy.txt

COPY api ./api
COPY model/fruitveg_int8.tflite ./model/fruitveg_int8.tflite
COPY model/metrics.json            ./model/metrics.json  
COPY data/price_list.csv ./data/price_list.csv
COPY data/dataset/train ./data/dataset/train  

EXPOSE 8000
CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]
